=== bizysoft/bizyStore/bizySoft/config/bizySoft.dtd
<!ELEMENT bizySoft            (appName, bizyStore?, rest?, options?)>
  <!ELEMENT appName             (#PCDATA)>
  <!ELEMENT bizyStore           (database+, options?)>
  <!ELEMENT options             (#PCDATA)>
  <!ELEMENT database            (id, interface, host?, port?, socket?, name, schema?, user?, password?, charset?, tables?, relationships?, pdoOptions?, pdoPrepareOptions?, modelPrepareOptions?)>
  <!ELEMENT relationships       (foreignKeys?, recursive?)>
  <!ELEMENT rest                (services?, options?)>
  <!ELEMENT services            (#PCDATA)>
  <!ELEMENT id                  (#PCDATA)>
  <!ELEMENT interface           (#PCDATA)>
  <!ELEMENT host                (#PCDATA)>
  <!ELEMENT port                (#PCDATA)>
  <!ELEMENT socket              (#PCDATA)>
  <!ELEMENT name                (#PCDATA)>
  <!ELEMENT schema              (#PCDATA)>
  <!ELEMENT user                (#PCDATA)>
  <!ELEMENT password            (#PCDATA)>
  <!ELEMENT charset             (#PCDATA)>
  <!ELEMENT tables              (#PCDATA)>
  <!ELEMENT recursive           (#PCDATA)>
  <!ELEMENT foreignKeys         (#PCDATA)>
  <!ELEMENT pdoOptions          (#PCDATA)>
  <!ELEMENT pdoPrepareOptions   (#PCDATA)>
  <!ELEMENT modelPrepareOptions (#PCDATA)>

=== bizysoft/bizyStore/bizySoft/config/unitTestExample.xml
<?xml version="1.0"?>
<!DOCTYPE bizySoft SYSTEM "file:///path/to/bizySoft/config/bizySoft.dtd">
<!-- 
	* This is an example of the bizySoftConfig file that is used to test bizyStore.
	*
	* An SQLite database and configuration has been provided as a default in the bizySoft/examples/db directory 
	* for unit tests and examples.
	* 
	* The bizySoft/tests/testData directory in this distribution has database scripts for each db interface.
	* You can run these into your database(s) to generate the tables required for the unit tests. 
	* 
-->
<bizySoft>
	<!-- 
	* The unit tests are written to reference <appName> as a namespace.
	* It should remain unchanged in the bizySoftConfig file for unit test execution. 
	-->
	<appName>unitTest</appName> 
	<bizyStore>
	<!-- 
	* This is the default database provided with the distribution in the bizySoft/examples/db directory.
	*
	* Change the details to suit your bizyStore installation.
	-->
		<database>
			<id>A</id>
			<interface>SQLite</interface>
			<name>/path/to/bizySoft/examples/db/bizy.db</name><!-- Change this to suit the path to the bizySoft directory -->
			<relationships>
				<foreignKeys>
				<!-- 
					The unit tests rely on this entry.
					The uniqueKeyMembership table in this database is purposely not configured with foreign keys, but foreign key 
					relationships can be realised by bizyStore with this config declaration.
				-->
					uniqueKeyMembership(memberFirstName.memberLastName.memberDob) => uniqueKeyMember(firstName.lastName.dob);
				</foreignKeys>
			</relationships>
			<pdoOptions>
				PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION;
				PDO::ATTR_EMULATE_PREPARES => FALSE
			</pdoOptions>
		</database>
	<!--
		* The following are examples of configuration for other databases that are supported.
		* 
		* Note that the <relationships> tag contains foreign key declarations that the unit tests rely on. It should be included 
		* for each database that you want to do unit tests on.
		* 
		* Change the details to suit your database(s). The <id></id> should be unique in this file.
	-->
	<!--  
		<database>
			<id>B</id>
			<interface>MySQL</interface>
			<host>your MySql host name or IP address</host>
			<name>your MySQL databse name</name>
			<user>your MySQL databse user</user>
			<password>your password for user</password>
				<relationships>
					<foreignKeys>
						uniqueKeyMembership(memberFirstName.memberLastName.memberDob) => uniqueKeyMember(firstName.lastName.dob);
					</foreignKeys>
				</relationships>
			<pdoOptions>
				PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION;
				PDO::ATTR_EMULATE_PREPARES => FALSE
			</pdoOptions>
		</database>
	-->
	</bizyStore>
</bizySoft>

=== bizysoft/bizyStore/bizySoft/config/bizyStoreExample.xml
<?xml version="1.0"?>
<!DOCTYPE bizySoft SYSTEM "file:///path/to/bizySoft/config/bizySoft.dtd">
<!-- 
	* This is the bizySoftConfig file that is used by the bizyStore examples. In a run time environment 
	* this file would normally be named bizySoftConfig.xml or yourDomainName.xml. (e.g. yourdomain.com.xml).
	*
	* If you have installed the bizySoft directory into your hosted environment's DOCUMENT_ROOT you should use a 
	* referenced config file to refer to this file in your website's 'account home directory'. (see bizyStoreExampleReferenced.xml)
	* 
	* It uses the SQLite database provided with the distribution in the bizySoft/examples/db directory.  
	*
	* You should change the above dtd to suit your installation. You can then change the config to suit your database, 
	* leaving the <appName> as is.
-->
<bizySoft>
<!-- The examples are written to reference <appName> as a namespace. It should remain unchanged . -->
	<appName>bizyStoreExample</appName> 
	<bizyStore>
		<database>
			<id>A</id>
			<interface>SQLite</interface>
			<name>/path/to/bizySoft/examples/db/bizy.db</name> <!-- Change this to suit the path to bizySoft -->
			<pdoOptions>
				PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION;
				PDO::ATTR_EMULATE_PREPARES => FALSE
			</pdoOptions>
		</database>
	</bizyStore>
</bizySoft>
